language: generic 
sudo: required 
services:
 - docker

before_install:
 - docker build -t ashwin15021/docker-react -f Dockerfile.dev .

script:
 - docker run -e CI=true ashwin15021/docker-react npm run test